from ubuntu:16.04
MAINTAINER Saket Kumar Choudhary <saket@impel.io>

RUN apt-get update --fix-missing && \
    apt-get -y upgrade && \
    apt-get install -y python3-pip

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get -y install default-jre-headless && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# --------------------------------------------------------------------------------------------------
# install python packages
# --------------------------------------------------------------------------------------------------
COPY ./requirements.txt /
RUN pip3 install -r /requirements.txt && rm /requirements.txt


# --------------------------------------------------------------------------------------------------
# copy src code and scripts into root dir /
# the crawler.py code assumes this dir structure
# --------------------------------------------------------------------------------------------------
COPY ./bank_transaction_platform/deployment/app.py /app.py
COPY ./bank_transaction_platform /bank_transaction_platform
COPY ./bank_transaction_platform/src /src

# --------------------------------------------------------------------------------------------------
# add entrypoint for the container
# --------------------------------------------------------------------------------------------------
ADD ./bank_transaction_platform/scripts/entrypoint.sh /bin/entrypoint.sh
RUN chmod +x /bin/entrypoint.sh
ENTRYPOINT ["/bin/entrypoint.sh"]